name: Deploy to GitHub Pages

permissions:
  contents: write
  pages: write

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps: 
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: nbdev docs
      uses: fastai/workflows/quarto-ghp@master
