name: CI
on:  [workflow_dispatch, pull_request, push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps: 
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: nbdev
      uses: fastai/workflows/nbdev-ci@master
    
